### PR TITLE
Allow swc files without a soma to be loaded

### PR DESCRIPTION
**Pull request by IgorTatarnikov**
Before submitting a pull request (PR), please read the [contributing guide](https://github.com/brainglobe/.github/blob/main/CONTRIBUTING.md).

Please fill out as much of this template as you can, but if you have any problems or questions, just leave a comment and we will help out :)

## Description

**What is this PR**

- [x] Bug fix
- [ ] Addition of a new feature
- [ ] Other

**Why is this PR needed?**
See https://forum.image.sc/t/brainrender-error-when-rendering-my-own-neuron-morphology/95389/5

**What does this PR do?**
Allows the `load_from_swc` and `create_mesh` functions to run when the provided swc file/Neuron object has no soma.

## References

Please reference any existing issues/PRs that relate to this PR.

## How has this PR been tested?
Tested using the user provided swc file, along with the standard `brainrender` swc test [file](https://github.com/brainglobe/brainrender/blob/main/brainrender/resources/neuron1.swc). Both are able to be rendered without errors now.

## Is this a breaking change?
No.

## Does this PR require an update to the documentation?
No.

## Checklist:

- [x] The code has been tested locally
- [x] The code has been formatted with [pre-commit](https://pre-commit.com/)

### CODE REVIEW

**Comment by adamltyson** [comment]
@IgorTatarnikov when I run it on the data without a soma, I get:

>morphio._morphio.MissingParentError: 
Sample id: 1 refers to non-existant parent ID: 0

Am I missing something?

**Comment by IgorTatarnikov** [comment]
Hmm, that's odd. Which swc file are you using?

**Comment by IgorTatarnikov** [comment]
I'm able to run it with the same file. I'll try downloading the file again and running it in a fresh environment.

**Comment by IgorTatarnikov** [comment]
I can't seem to replicate it, everything runs smoothly in a fresh environment.

**Comment by adamltyson** [comment]
Ok finally after starting from scratch with **everything**, it works fine. No idea what's going on with my system.

**Review by adamltyson — APPROVED** [review]

**Comment by adamltyson** [comment]
Will release and report back on image.sc.

**Pull request merged**
