### PR TITLE
Compatibility for new NeuroM versions

### PR DESCRIPTION
**Pull request by adrien-berchet**
Hello,
I would need compatibility for new versions of NeuroM. As far as I can see, only a change for an import is required.

### CODE REVIEW

**Comment by FedeClaudi** [comment]
Did you use the modified version, and did it work correctly? Have you tried using it to visualize neuron morphologies with Brainrender?

**Comment by adrien-berchet** [comment]
I tried the script `examples/neurons.py` from `brainrender` (the only one that uses `morphapi`) and it seems to work properly. I get many VTK errors reported in the console but in the end I get the following scene:
image

**Comment by FedeClaudi** [comment]
> I get many VTK errors reported in the console 

Yep you can ignore those. Looks good thank you!

**Comment by adrien-berchet** [comment]
Ok, cool, thanks!

**Pull request merged**
