### PR TITLE
Test: Fix Path for Windows

### PR DESCRIPTION
**Pull request by adrien-berchet**
## Description

**What is this PR**

- [ ] Bug fix
- [ ] Addition of a new feature
- [x] Other

**Why is this PR needed?**

The CI fails on the Windows runner.

**What does this PR do?**

Fix the paths for Windows.

## How has this PR been tested?

The tests were failing and now they should work.

## Is this a breaking change?

No

## Does this PR require an update to the documentation?

No

## Checklist:

- [ ] The code has been tested locally
- [ ] Tests have been added to cover all new functionality (unit & integration)
- [ ] The documentation has been updated to reflect any changes
- [x] The code has been formatted with [pre-commit](https://pre-commit.com/)

### CODE REVIEW

**Review by alessandrofelder — APPROVED** [review]
Thanks @adrien-berchet

**Comment by adrien-berchet** [comment]
You're welcome!
And note that the release `0.2.2` could not be published because of this issue.

**Comment by alessandrofelder** [comment]
Are you happy to publish the next patch release?

**Comment by adrien-berchet** [comment]
I tested the main branch in my workflow and it looks fine so I pushed the `0.2.3` release.

**Pull request merged**
