### PR TITLE
Fix SSL verification and add CI tests

### PR DESCRIPTION
**Pull request by adrien-berchet**
* Fix SSL verification when local cipher is different from the server one.
* Fix the behavior of `invert_dims` in `morphapi.morphology.morphology.Neuron`.
* Fix compatibility for py39.
* Use setuptools_scm for version management.
* Use tox to run the tests.
* Run black.
* Add tests in CI and auto upload to pypi for new tags.

### CODE REVIEW

**Comment by adrien-berchet** [comment]
The tests pass in CI. Now all you have to do is to set your Pypi token into the `PYPI_API_TOKEN` environment secret. Then each new tag will be automatically pushed to Pypi.

**Comment by adrien-berchet** [comment]
ping @arnaudon

**Comment by arnaudon** [comment]
Nice!

**Comment by FedeClaudi** [comment]
looks good, is it ready for merging?

**Comment by adrien-berchet** [comment]
For me it is.
Can you just check the changes for the `revert_dims` behavior please @FedeClaudi (in `morphology.py`)? I am surprised because as far as I understand this part of the code just never worked.

**Pull request merged**
