### PR TITLE
Update supported Python versions

### PR DESCRIPTION
**Pull request by adamltyson**

### CODE REVIEW

**Comment by adamltyson** [comment]
Tests are failing due to [this issue](https://github.com/AllenInstitute/AllenSDK/issues/2744). Unless the Allen can address this quickly, I'm not sure what the solution is. Ignore these tests? Be ruthless and remove any feature using third party tools we can't rely on? Hold off updating to 3.11 for a while?

Although 3.12 is the issue here, the AllenSDK pins scipy, xarray, pandas and numpy to fairly old versions which may cause issues when installing the metapackage.

**Comment by alessandrofelder** [comment]
> Be ruthless and remove any feature using third party tools we can't rely on?

Not sure either - I'd rather not ignore tests for 3.11 if possible, and we've put in a lot of effort to be able to move to 3.11.
Is contributing to the `allensdk` an option?

**Comment by adamltyson** [comment]
Sorry, my mistake. Just FYI it's 3.12 causing the problem.

**Comment by adamltyson** [comment]
We may just have to bite the bullet and remove AllenSDK from all of BrainGlobe. It works well in it's own environment, but it doesn't seem to be maintained sufficiently to rely on as a dependency.

**Comment by adamltyson** [comment]
I've updated this PR to only remove 3.9 (not add 3.12).

I've raised https://github.com/brainglobe/morphapi/issues/67 and https://github.com/brainglobe/morphapi/issues/68 to track the issues raised here.

**Review by alessandrofelder — APPROVED** [review]
Approving as test failures related to external websites.

**Pull request merged**
